### ISSUE TITLE
Add python and ruby

### ISSUE THREAD

**Issue by tdi** [emmanuel-keller/github-language-statistics#3]
Without these languages, this comparison is not full.

**Comment by emmanuel-keller** [comment]
True, work in progress...

**Comment by tdi** [comment]
Maybe perl too :)

**Comment by emmanuel-keller** [comment]
Yes, and Scala :D .. I am going to put all together

**Comment by servusoft** [comment]
According to Github's logic CSS is also a language ;)

**Comment by emmanuel-keller** [comment]
Yeah, but the goal here is to focus mainly on programming language. I think there is 20 other languages detected ...

**Comment by tdi** [comment]
Can C be distinguished from C++ ?

**Comment by emmanuel-keller** [comment]
Yes. I am currently adding the following:
"C", "Objective C", "Perl", "Php", "Python", "Ruby", "Scala"
It will be updated within half an hour I think.

**Comment by emmanuel-keller** [comment]
Here they are.

**Comment by relrod** [comment]
Haskell? :)

**Comment by emmanuel-keller** [comment]
@relrod  Added  :)

**Comment by relrod** [comment]
Woot, thanks!
