### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by edjiang** [emmanuel-keller/github-language-statistics#5]
The number of Objective-C repos in this seems really off, and doesn't pass my "sniff test". 

As an iOS developer, I'm very hesitant to believe that there are more active Obj-C repos than JS, for instance. 

Any ideas why this might be the case? I'll try to look into this data as well, and report back here if I find anything =]

**Comment by servusoft** [comment]
Google Trends scores Objective-C significantly lower:
https://www.google.com/trends/explore?cat=31&date=today%2012-m&q=%2Fm%2F0jgqg,%2Fm%2F07sbkfb,%2Fm%2F02p97,Python,%2Fm%2F05q31

**Comment by emmanuel-keller** [comment]
I am going to filter the repos by using three more filters:
- More than 0 stars.
- At least 1 fork.
- The size of the project should be greater than 10k. 

Here is the reference API:
https://api.github.com/search/repositories?q=language%3AC%2B%2B%20pushed%3A2016-11%20stars%3A%3E0%20forks%3A%3E0%20size%3A%3E10

**Comment by servusoft** [comment]
I have only  "language": "C++" in the query. it's only for C++?

**Comment by emmanuel-keller** [comment]
Yes. There is one request per language and per period of time.

**Comment by sophiajt** [comment]
If you look through the languages, Objective C will return results for a number of different languages.  It seems searching for it is broken (perhaps because of spaces?)

**Comment by emmanuel-keller** [comment]
You're right. I am adding quotes.

The wrong API request returns Objective C and C repos (4917).

https://api.github.com/search/repositories?q=stars:%3E0+forks:%3E0+size:%3E10+language:Objective+C+pushed:2016-01-01..2016-01-31

The fixed API request (with quotes) returns the right count: 1010.

https://api.github.com/search/repositories?q=stars:>0+forks:>0+size:>10+language:%22Objective+C%22+pushed:2016-01-01..2016-01-31

Fix in progress..

**Comment by emmanuel-keller** [comment]
@jonathandturner  Thanks ! Fixed and updated.

**Comment by edjiang** [comment]
Thanks @emmanuel-keller!
